[2023-12-03 17:30:16,164] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_automation_daily.testing manual__2023-12-03T17:30:10.839543+00:00 [queued]>
[2023-12-03 17:30:16,200] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_automation_daily.testing manual__2023-12-03T17:30:10.839543+00:00 [queued]>
[2023-12-03 17:30:16,201] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-12-03 17:30:16,202] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2023-12-03 17:30:16,203] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-12-03 17:30:16,254] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): testing> on 2023-12-03 17:30:10.839543+00:00
[2023-12-03 17:30:16,275] {standard_task_runner.py:52} INFO - Started process 798 to run task
[2023-12-03 17:30:16,284] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_automation_daily', 'testing', 'manual__2023-12-03T17:30:10.839543+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmph6_apl_q', '--error-file', '/tmp/tmp7t23mqab']
[2023-12-03 17:30:16,286] {standard_task_runner.py:80} INFO - Job 27: Subtask testing
[2023-12-03 17:30:16,487] {task_command.py:369} INFO - Running <TaskInstance: dag_automation_daily.testing manual__2023-12-03T17:30:10.839543+00:00 [running]> on host b69c54045741
[2023-12-03 17:30:16,748] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sebastiancahyoardhiiswara@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag_automation_daily
AIRFLOW_CTX_TASK_ID=testing
AIRFLOW_CTX_EXECUTION_DATE=2023-12-03T17:30:10.839543+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-12-03T17:30:10.839543+00:00
[2023-12-03 17:30:16,753] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-12-03 17:30:16,753] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python codes/test.py']
[2023-12-03 17:30:16,799] {subprocess.py:85} INFO - Output:
[2023-12-03 17:30:18,535] {subprocess.py:92} INFO - mysql+mysqlconnector://root:mysql@mysql-db:3306/mysql
[2023-12-03 17:30:18,535] {subprocess.py:92} INFO - postgresql://***:***@postgres-db:5432/***
[2023-12-03 17:30:18,536] {subprocess.py:92} INFO - None
[2023-12-03 17:30:18,536] {subprocess.py:92} INFO - user: postgres
[2023-12-03 17:30:18,536] {subprocess.py:92} INFO - password: postgres
[2023-12-03 17:30:18,537] {subprocess.py:92} INFO - db: dwh
[2023-12-03 17:30:18,726] {subprocess.py:96} INFO - Command exited with return code 0
[2023-12-03 17:30:18,798] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag_automation_daily, task_id=testing, execution_date=20231203T173010, start_date=20231203T173016, end_date=20231203T173018
[2023-12-03 17:30:18,873] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-12-03 17:30:18,945] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
