[2023-12-03 17:57:46,396] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_automation_daily.testing manual__2023-12-03T17:57:36.718105+00:00 [queued]>
[2023-12-03 17:57:46,448] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_automation_daily.testing manual__2023-12-03T17:57:36.718105+00:00 [queued]>
[2023-12-03 17:57:46,448] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-12-03 17:57:46,449] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2023-12-03 17:57:46,455] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-12-03 17:57:46,520] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): testing> on 2023-12-03 17:57:36.718105+00:00
[2023-12-03 17:57:46,539] {standard_task_runner.py:52} INFO - Started process 240 to run task
[2023-12-03 17:57:46,548] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_automation_daily', 'testing', 'manual__2023-12-03T17:57:36.718105+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpdyl4idzh', '--error-file', '/tmp/tmpkv8_9p1d']
[2023-12-03 17:57:46,550] {standard_task_runner.py:80} INFO - Job 34: Subtask testing
[2023-12-03 17:57:46,867] {task_command.py:369} INFO - Running <TaskInstance: dag_automation_daily.testing manual__2023-12-03T17:57:36.718105+00:00 [running]> on host c9140d11a0a8
[2023-12-03 17:57:47,367] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sebastiancahyoardhiiswara@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag_automation_daily
AIRFLOW_CTX_TASK_ID=testing
AIRFLOW_CTX_EXECUTION_DATE=2023-12-03T17:57:36.718105+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-12-03T17:57:36.718105+00:00
[2023-12-03 17:57:47,374] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-12-03 17:57:47,374] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python codes/test.py']
[2023-12-03 17:57:47,434] {subprocess.py:85} INFO - Output:
[2023-12-03 17:57:52,935] {subprocess.py:92} INFO - mysql+mysqlconnector://root:mysql@db_mysql_staging:3306/mysql
[2023-12-03 17:57:52,936] {subprocess.py:92} INFO - postgresql://***:***@db_postgres_dwh:5432/***
[2023-12-03 17:57:52,937] {subprocess.py:92} INFO - None
[2023-12-03 17:57:52,937] {subprocess.py:92} INFO - user: postgres
[2023-12-03 17:57:52,938] {subprocess.py:92} INFO - password: postgres
[2023-12-03 17:57:52,938] {subprocess.py:92} INFO - db: dwh
[2023-12-03 17:57:53,125] {subprocess.py:96} INFO - Command exited with return code 0
[2023-12-03 17:57:53,217] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag_automation_daily, task_id=testing, execution_date=20231203T175736, start_date=20231203T175746, end_date=20231203T175753
[2023-12-03 17:57:53,278] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-12-03 17:57:53,359] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
