[2023-12-03 18:24:04,010] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_automation_daily.running_automation manual__2023-12-03T18:24:00.682672+00:00 [queued]>
[2023-12-03 18:24:04,030] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_automation_daily.running_automation manual__2023-12-03T18:24:00.682672+00:00 [queued]>
[2023-12-03 18:24:04,031] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-12-03 18:24:04,031] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2023-12-03 18:24:04,031] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-12-03 18:24:04,066] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): running_automation> on 2023-12-03 18:24:00.682672+00:00
[2023-12-03 18:24:04,082] {standard_task_runner.py:52} INFO - Started process 650 to run task
[2023-12-03 18:24:04,088] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_automation_daily', 'running_automation', 'manual__2023-12-03T18:24:00.682672+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpytk9_n6k', '--error-file', '/tmp/tmpn0ycde2n']
[2023-12-03 18:24:04,090] {standard_task_runner.py:80} INFO - Job 45: Subtask running_automation
[2023-12-03 18:24:04,741] {task_command.py:369} INFO - Running <TaskInstance: dag_automation_daily.running_automation manual__2023-12-03T18:24:00.682672+00:00 [running]> on host c9140d11a0a8
[2023-12-03 18:24:05,618] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sebastiancahyoardhiiswara@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag_automation_daily
AIRFLOW_CTX_TASK_ID=running_automation
AIRFLOW_CTX_EXECUTION_DATE=2023-12-03T18:24:00.682672+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-12-03T18:24:00.682672+00:00
[2023-12-03 18:24:05,625] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-12-03 18:24:05,625] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python codes/automation.py']
[2023-12-03 18:24:05,672] {subprocess.py:85} INFO - Output:
[2023-12-03 18:24:10,655] {subprocess.py:92} INFO - (psycopg2.errors.DependentObjectsStillExist) cannot drop table dim_province because other objects depend on it
[2023-12-03 18:24:10,656] {subprocess.py:92} INFO - DETAIL:  constraint dim_district_province_id_fkey on table dim_district depends on table dim_province
[2023-12-03 18:24:10,656] {subprocess.py:92} INFO - HINT:  Use DROP ... CASCADE to drop the dependent objects too.
[2023-12-03 18:24:10,657] {subprocess.py:92} INFO - 
[2023-12-03 18:24:10,657] {subprocess.py:92} INFO - [SQL:
[2023-12-03 18:24:10,658] {subprocess.py:92} INFO - DROP TABLE dim_province]
[2023-12-03 18:24:10,658] {subprocess.py:92} INFO - (Background on this error at: http://sqlalche.me/e/14/2j85)
[2023-12-03 18:24:10,842] {subprocess.py:96} INFO - Command exited with return code 0
[2023-12-03 18:24:10,889] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag_automation_daily, task_id=running_automation, execution_date=20231203T182400, start_date=20231203T182404, end_date=20231203T182410
[2023-12-03 18:24:10,939] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-12-03 18:24:10,980] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
