[2023-12-03 18:05:52,237] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_automation_daily.testing manual__2023-12-03T18:05:49.653907+00:00 [queued]>
[2023-12-03 18:05:52,259] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_automation_daily.testing manual__2023-12-03T18:05:49.653907+00:00 [queued]>
[2023-12-03 18:05:52,260] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-12-03 18:05:52,260] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2023-12-03 18:05:52,261] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-12-03 18:05:52,321] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): testing> on 2023-12-03 18:05:49.653907+00:00
[2023-12-03 18:05:52,390] {standard_task_runner.py:52} INFO - Started process 380 to run task
[2023-12-03 18:05:52,400] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_automation_daily', 'testing', 'manual__2023-12-03T18:05:49.653907+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpsg25uifv', '--error-file', '/tmp/tmpfeg29vxs']
[2023-12-03 18:05:52,404] {standard_task_runner.py:80} INFO - Job 39: Subtask testing
[2023-12-03 18:05:52,671] {task_command.py:369} INFO - Running <TaskInstance: dag_automation_daily.testing manual__2023-12-03T18:05:49.653907+00:00 [running]> on host c9140d11a0a8
[2023-12-03 18:05:52,930] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sebastiancahyoardhiiswara@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag_automation_daily
AIRFLOW_CTX_TASK_ID=testing
AIRFLOW_CTX_EXECUTION_DATE=2023-12-03T18:05:49.653907+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-12-03T18:05:49.653907+00:00
[2023-12-03 18:05:52,935] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-12-03 18:05:52,940] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python codes/test.py']
[2023-12-03 18:05:53,019] {subprocess.py:85} INFO - Output:
[2023-12-03 18:05:54,722] {subprocess.py:92} INFO - mysql+mysqlconnector://root:mysql@db_mysql_staging:3306/mysql
[2023-12-03 18:05:54,723] {subprocess.py:92} INFO - postgresql://***:***@db_postgres_dwh:5432/***
[2023-12-03 18:05:54,723] {subprocess.py:92} INFO - None
[2023-12-03 18:05:54,724] {subprocess.py:92} INFO - user: postgres
[2023-12-03 18:05:54,724] {subprocess.py:92} INFO - password: postgres
[2023-12-03 18:05:54,724] {subprocess.py:92} INFO - db: dwh
[2023-12-03 18:05:54,853] {subprocess.py:96} INFO - Command exited with return code 0
[2023-12-03 18:05:54,916] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag_automation_daily, task_id=testing, execution_date=20231203T180549, start_date=20231203T180552, end_date=20231203T180554
[2023-12-03 18:05:54,958] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-12-03 18:05:55,019] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
