[2023-12-03 17:34:28,258] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_automation_daily.testing manual__2023-12-03T17:34:22.787050+00:00 [queued]>
[2023-12-03 17:34:28,391] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_automation_daily.testing manual__2023-12-03T17:34:22.787050+00:00 [queued]>
[2023-12-03 17:34:28,392] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-12-03 17:34:28,392] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2023-12-03 17:34:28,393] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-12-03 17:34:28,529] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): testing> on 2023-12-03 17:34:22.787050+00:00
[2023-12-03 17:34:28,556] {standard_task_runner.py:52} INFO - Started process 198 to run task
[2023-12-03 17:34:28,602] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_automation_daily', 'testing', 'manual__2023-12-03T17:34:22.787050+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp21w7i2kt', '--error-file', '/tmp/tmphmalav2v']
[2023-12-03 17:34:28,619] {standard_task_runner.py:80} INFO - Job 29: Subtask testing
[2023-12-03 17:34:29,474] {task_command.py:369} INFO - Running <TaskInstance: dag_automation_daily.testing manual__2023-12-03T17:34:22.787050+00:00 [running]> on host 5a42a9fa2eef
[2023-12-03 17:34:30,060] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sebastiancahyoardhiiswara@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag_automation_daily
AIRFLOW_CTX_TASK_ID=testing
AIRFLOW_CTX_EXECUTION_DATE=2023-12-03T17:34:22.787050+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-12-03T17:34:22.787050+00:00
[2023-12-03 17:34:30,068] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-12-03 17:34:30,070] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python codes/test.py']
[2023-12-03 17:34:30,203] {subprocess.py:85} INFO - Output:
[2023-12-03 17:34:33,791] {subprocess.py:92} INFO - mysql+mysqlconnector://root:mysql@mysql-db:3306/mysql
[2023-12-03 17:34:33,791] {subprocess.py:92} INFO - postgresql://***:***@postgres-db:5432/***
[2023-12-03 17:34:33,791] {subprocess.py:92} INFO - postgresql://***:***@postgres-db:5432/***
[2023-12-03 17:34:33,792] {subprocess.py:92} INFO - user: postgres
[2023-12-03 17:34:33,792] {subprocess.py:92} INFO - password: postgres
[2023-12-03 17:34:33,792] {subprocess.py:92} INFO - db: dwh
[2023-12-03 17:34:34,007] {subprocess.py:96} INFO - Command exited with return code 0
[2023-12-03 17:34:34,615] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag_automation_daily, task_id=testing, execution_date=20231203T173422, start_date=20231203T173428, end_date=20231203T173434
[2023-12-03 17:34:34,977] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-12-03 17:34:35,274] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
